In [ ]:
# Loading data set

In [40]:
import pandas as pd

In [41]:
dataset = pd.read_csv('datasets/50_Startups.csv')

In [42]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [43]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [44]:
y = dataset.Profit

In [45]:
X = dataset[ ['R&D Spend', 'Administration', 'Marketing Spend', 'State'] ]

In [46]:
X.shape

(50, 4)

In [47]:
state_feature = X['State']

In [ ]:
# Lablel encoding for state variable as it has multicollinarity(multi varibale or categorical variable)

In [48]:
from sklearn.preprocessing import LabelEncoder

In [49]:
labelEncode = LabelEncoder()

In [50]:
labelEncodedState = labelEncode.fit_transform(state_feature)

In [51]:
reshapedLabelEncodedState = labelEncodedState.reshape(-1, 1)

In [52]:
reshapedLabelEncodedState.shape

(50, 1)

In [1]:
# loading OneHotEncoder for dummy variable i.e spliting categorial variables into columns or features so that we dont loose data 

In [53]:
from sklearn.preprocessing import OneHotEncoder

In [54]:
oneEncode = OneHotEncoder()

In [55]:
oneHotEncodedState = oneEncode.fit_transform(reshapedLabelEncodedState)

In [56]:
oneHotEncodedStateArray = oneHotEncodedState.toarray()

In [57]:
finalStateFeatures = oneHotEncodedStateArray[:, :2]

In [58]:
finalStateFeatures

array([[0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [60]:
X = X[['R&D Spend', 'Administration', 'Marketing Spend']]

In [61]:
X

R&D Spend  Administration  Marketing Spend
0   165349.20       136897.80        471784.10
1   162597.70       151377.59        443898.53
2   153441.51       101145.55        407934.54
3   144372.41       118671.85        383199.62
4   142107.34        91391.77        366168.42
5   131876.90        99814.71        362861.36
6   134615.46       147198.87        127716.82
7   130298.13       145530.06        323876.68
8   120542.52       148718.95        311613.29
9   123334.88       108679.17        304981.62
10  101913.08       110594.11        229160.95
11  100671.96        91790.61        249744.55
12   93863.75       127320.38        249839.44
13   91992.39       135495.07        252664.93
14  119943.24       156547.42        256512.92
15  114523.61       122616.84        261776.23
16   78013.11       121597.55        264346.06
17   94657.16       145077.58        282574.31
18   91749.16       114175.79        294919.57
19   86419.70       153514.11             0.00
20   76253.86       113867.30        298664.47
21   78389.47       153773.43        299737.29
22   73994.56       122782.75        303319.26
23   67532.53       105751.03        304768.73
24   77044.01        99281.34        140574.81
25   64664.71       139553.16        137962.62
26   75328.87       144135.98        134050.07
27   72107.60       127864.55        353183.81
28   66051.52       182645.56        118148.20
29   65605.48       153032.06        107138.38
30   61994.48       115641.28         91131.24
31   61136.38       152701.92         88218.23
32   63408.86       129219.61         46085.25
33   55493.95       103057.49        214634.81
34   46426.07       157693.92        210797.67
35   46014.02        85047.44        205517.64
36   28663.76       127056.21        201126.82
37   44069.95        51283.14        197029.42
38   20229.59        65947.93        185265.10
39   38558.51        82982.09        174999.30
40   28754.33       118546.05        172795.67
41   27892.92        84710.77        164470.71
42   23640.93        96189.63        148001.11
43   15505.73       127382.30         35534.17
44   22177.74       154806.14         28334.72
45    1000.23       124153.04          1903.93
46    1315.46       115816.21        297114.46
47       0.00       135426.92             0.00
48     542.05        51743.15             0.00
49       0.00       116983.80         45173.06

In [ ]:
# loading numpy for adding modified columns to original dataset

In [63]:
import numpy

In [66]:
finalDataSet = numpy.hstack( (X, finalStateFeatures) )

In [67]:
finalDataSet

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 0.0000000e+00,
        0.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 1.0000000e+00,
        0.0000000e+00],
       [1.5344151e+05, 1.0114555e+05, 4.0793454e+05, 0.0000000e+00,
        1.0000000e+00],
       [1.4437241e+05, 1.1867185e+05, 3.8319962e+05, 0.0000000e+00,
        0.0000000e+00],
       [1.4210734e+05, 9.1391770e+04, 3.6616842e+05, 0.0000000e+00,
        1.0000000e+00],
       [1.3187690e+05, 9.9814710e+04, 3.6286136e+05, 0.0000000e+00,
        0.0000000e+00],
       [1.3461546e+05, 1.4719887e+05, 1.2771682e+05, 1.0000000e+00,
        0.0000000e+00],
       [1.3029813e+05, 1.4553006e+05, 3.2387668e+05, 0.0000000e+00,
        1.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 0.0000000e+00,
        0.0000000e+00],
       [1.2333488e+05, 1.0867917e+05, 3.0498162e+05, 1.0000000e+00,
        0.0000000e+00],
       [1.0191308e+05, 1.1059411e+05, 2.2916095e+05, 0.0000000e+00,
        1.00

In [ ]:
# creating model with preprocessed data

In [68]:
from sklearn.linear_model import LinearRegression

In [69]:
model = LinearRegression()

In [ ]:
# loading to do train and test split for the data

In [72]:
from sklearn.model_selection import train_test_split

In [73]:
X_train, X_test, y_train, y_test = train_test_split( finalDataSet, y, test_size=0.33)

In [74]:
model.fit(X_train, y_train)

LinearRegression()

In [76]:
model.predict(X_test)

array([ 85076.49353987,  61584.74691128,  62114.42316411, 187672.77287081,
       103927.49285068, 172759.7490492 ,  51370.91424008, 102723.69415497,
       152678.49644211, 191101.15319863, 114615.07132487, 133055.19075603,
       154386.07752192,  48149.93194541, 163065.95154661, 130043.05203923,
       117473.26432949])

In [79]:
y_test

39     81005.76
43     69758.98
46     49490.75
1     191792.06
30     99937.59
3     182901.99
48     35673.41
33     96778.92
14    132602.65
0     192261.83
23    108733.99
18    124266.90
9     149759.96
47     42559.73
7     155752.60
17    125370.37
21    111313.02
Name: Profit, dtype: float64

In [ ]:
# for finding mean absoulte error for the predicted data for the model

In [77]:
from sklearn.metrics import mean_absolute_error

In [78]:
mean_absolute_error(model.predict(X_test), y_test)

7590.049519144895

In [80]:
model.coef_

array([ 7.84527948e-01, -3.33909150e-02,  2.81438383e-02, -1.45126833e+00,
        3.91426394e+03])